name: daily

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  score:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - run: npm run -s dev --workspace=runner >> packages/leaderboard/data/history.ndjson
        env:
          DEBUG: "runner*"
      - run: git status
        if: always()
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add packages/leaderboard/data/history.ndjson
          git commit -m "chore: update $(date +'%Y-%m-%d')"
          git push origin main
